# Generated by Django 4.0.3 on 2022-03-04 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('department', models.CharField(blank=True, choices=[('Bakery', 'Bakery'), ('Boulangerie', 'Boulangerie'), ('Supermarket', 'Supermarket'), ('Bar', 'Bar'), ('Snack', 'Snack'), ('Ice Cream', 'Ice Cream')], default='', max_length=500, null=True)),
                ('user_status', models.CharField(blank=True, choices=[('Employee', 'Employee'), ('Management', 'Management')], default='', max_length=500, null=True)),
                ('description', models.CharField(default='Opening Cash', max_length=200)),
                ('amount', models.FloatField(default=0.0)),
                ('account', models.CharField(blank=True, choices=[('Opening Cash', 'Opening Cash'), ('Closing Cash', 'Closing Cash'), ('Accounts Receivables Opening Bal', 'Accounts Receivables Opening Bal'), ('Accounts Payables Opening Bal', 'Accounts Payables Opening Bal'), ('Creditors Opening Bal', 'Creditors Opening Bal'), ('Bank Opening Bal', 'Bank Opening Bal')], default='', max_length=500, null=True)),
                ('account_dr', models.CharField(blank=True, choices=[('Opening Cash', 'Opening Cash'), ('Closing Cash', 'Closing Cash'), ('Accounts Receivables Opening Bal', 'Accounts Receivables Opening Bal'), ('Accounts Payables Opening Bal', 'Accounts Payables Opening Bal'), ('Creditors Opening Bal', 'Creditors Opening Bal'), ('Bank Opening Bal', 'Bank Opening Bal')], default='', max_length=500, null=True)),
                ('account_cr', models.CharField(blank=True, choices=[('Opening Cash', 'Opening Cash'), ('Closing Cash', 'Closing Cash'), ('Accounts Receivables Opening Bal', 'Accounts Receivables Opening Bal'), ('Accounts Payables Opening Bal', 'Accounts Payables Opening Bal'), ('Creditors Opening Bal', 'Creditors Opening Bal'), ('Bank Opening Bal', 'Bank Opening Bal')], default='', max_length=500, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OpeningBalance',
                'verbose_name_plural': 'OpeningBalances',
            },
        ),
    ]
