# Generated by Django 4.0.3 on 2022-03-04 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openingbalance',
            options={'verbose_name': 'Opening Balance', 'verbose_name_plural': 'Opening Balances'},
        ),
        migrations.RemoveField(
            model_name='openingbalance',
            name='account_cr',
        ),
        migrations.RemoveField(
            model_name='openingbalance',
            name='account_dr',
        ),
    ]
