# Generated by Django 4.0.3 on 2022-03-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_ledger', '0003_openingbalance_customer_institution_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='account_cr',
            field=models.CharField(blank=True, choices=[('Accounts Receivables', 'Accounts Receivables'), ('Sales', 'Sales')], default='', max_length=500, null=True, verbose_name='Account Credit'),
        ),
        migrations.AlterField(
            model_name='income',
            name='account_dr',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Closing Cash', 'Closing Cash')], default='', max_length=500, null=True, verbose_name='Account Debit'),
        ),
    ]
