# Generated by Django 4.0.3 on 2022-03-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_ledger', '0004_alter_income_account_cr_alter_income_account_dr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='department',
            field=models.CharField(blank=True, choices=[('Bakery', 'Bakery'), ('Boulangerie', 'Boulangerie'), ('Supermarket', 'Supermarket'), ('Bar', 'Bar'), ('Snack', 'Snack'), ('Ice Cream', 'Ice Cream')], default='', max_length=500, null=True),
        ),
    ]
