# Generated by Django 4.0.3 on 2022-03-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_ledger', '0006_purchases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='account_cr',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Creditors', 'Creditors')], default='', max_length=500, null=True, verbose_name='Account Credit'),
        ),
    ]
