# Generated by Django 4.0.3 on 2022-03-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_ledger', '0007_alter_purchases_account_cr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchases',
            name='customer_institution',
        ),
        migrations.AddField(
            model_name='purchases',
            name='supplier',
            field=models.CharField(default='', max_length=200, verbose_name='Supplier'),
        ),
    ]
