# Generated by Django 4.0.3 on 2022-03-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_ledger', '0009_alter_purchases_options_purchases_due_date_creditors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='due_date',
            field=models.DateField(default='', verbose_name='Due Date'),
        ),
    ]
