# Generated by Django 4.0.3 on 2022-03-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_ledger', '0010_alter_purchases_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='due_date',
            field=models.DateField(blank=True, default='', null=True, verbose_name='Due Date'),
        ),
    ]
