# Generated by Django 4.0.3 on 2022-03-04 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general_ledger', '0012_alter_creditors_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchases',
            options={'verbose_name': 'Purchases', 'verbose_name_plural': 'Purchases'},
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('department', models.CharField(blank=True, choices=[('Bakery', 'Bakery'), ('Boulangerie', 'Boulangerie'), ('Supermarket', 'Supermarket'), ('Bar', 'Bar'), ('Snack', 'Snack'), ('Ice Cream', 'Ice Cream'), ('WholeSale', 'WholeSale')], default='', max_length=500, null=True)),
                ('user_status', models.CharField(blank=True, choices=[('Employee', 'Employee'), ('Management', 'Management')], default='', max_length=500, null=True)),
                ('invoice_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Invoice Id')),
                ('supplier', models.CharField(default='', max_length=200, verbose_name='Supplier')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.FloatField(default=0.0)),
                ('account_dr', models.CharField(blank=True, choices=[('Airtime Expense', 'Airtime Expense'), ('Miscelleanous Expenses', 'Miscelleanous Expenses'), ('Tape expense', 'Tape expense'), ('Bike Maintanance Expense', 'Bike Maintanance Expense'), ('Bike Repairs Expense', 'Bike Repairs Expense'), ('Computer Repairs Expense', 'Computer Repairs Expense'), ('Cooler Maintainance expense', 'Cooler Maintainance expense'), ('Electrical repairs expense', 'Electrical repairs expense'), ('Fridge Repairs Expense', 'Fridge Repairs Expense'), ('Generator Maintainance Expense', 'Generator Maintainance Expense'), ('Internet Bill Expense', 'Internet Bill Expense'), ('Other Repairs Expense', 'Other Repairs Expense'), ('Oven Maintainance expenses', 'Oven Maintainance expenses'), ('Van Maintainance expense', 'Van Maintainance expense'), ('Van Repairs Expense', 'Van Repairs Expense'), ('Cable Expenses', 'Cable Expenses'), ('Electricity Bill Expense', 'Electricity Bill Expense'), ('Water Bill Expense', 'Water Bill Expense'), ('Charges expense', 'Charges expense'), ('Cleaning Expense', 'Cleaning Expense'), ('Commission Expense', 'Commission Expense'), ('Health Expense', 'Health Expense'), ('Insurance Expense', 'Insurance Expense'), ('Off Loading Expense', 'Off Loading Expense'), ('Provision for Loss Product Expense', 'Provision for Loss Product Expense'), ('Hygiene and Sanitation Expenses', 'Hygiene and Sanitation Expenses'), ('Social Insurance Expense', 'Social Insurance Expense'), ('Rents Expense', 'Rents Expense'), ('Stationaries', 'Stationaries'), ('Direct Labour Expense', 'Direct Labour Expense'), ('InDirect Labour Expense', 'InDirect Labour Expense'), ('Fuel expense', 'Fuel expense'), ('Transportation Expense', 'Transportation Expense'), ('Gas Expense', 'Gas Expense'), ('Salary Expenses', 'Salary Expenses'), ('Allowance Expense', 'Allowance Expense'), ('Tax Expense', 'Tax Expense'), ('Depreciation Expense', 'Depreciation Expense')], default='', max_length=500, null=True, verbose_name='Account Debit')),
                ('account_cr', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Airtime Expense Payables', 'Airtime Expense Payables'), ('Miscelleanous Expenses Payables', 'Miscelleanous Expenses Payables'), ('Tape expense Payables', 'Tape expense Payables'), ('Bike Maintanance Expense Payables', 'Bike Maintanance Expense Payables'), ('Bike Repairs Expense Payables', 'Bike Repairs Expense Payables'), ('Computer Repairs Expense Payables', 'Computer Repairs Expense Payables'), ('Cooler Maintainance expense Payables', 'Cooler Maintainance expense Payables'), ('Electrical repairs expense Payables', 'Electrical repairs expense Payables'), ('Fridge Repairs Expense Payables', 'Fridge Repairs Expense Payables'), ('Generator Maintainance Expense Payables', 'Generator Maintainance Expense Payables'), ('Internet Bill Expense Payables', 'Internet Bill Expense Payables'), ('Other Repairs Expense Payables', 'Other Repairs Expense Payables'), ('Oven Maintainance expenses Payables', 'Oven Maintainance expenses Payables'), ('Van Maintainance expense Payables', 'Van Maintainance expense Payables'), ('Van Repairs Expense Payables', 'Van Repairs Expense Payables'), ('Cable Expenses Payables', 'Cable Expenses Payables'), ('Electricity Bill Expense Payables', 'Electricity Bill Expense Payables'), ('Water Bill Expense Payables', 'Water Bill Expense Payables'), ('Charges expense Payables', 'Charges expense Payables'), ('Cleaning Expense Payables', 'Cleaning Expense Payables'), ('Commission Expense Payables', 'Commission Expense Payables'), ('Health Expense Payables', 'Health Expense Payables'), ('Insurance Expense Payables', 'Insurance Expense Payables'), ('Off Loading Expense Payables', 'Off Loading Expense Payables'), ('Provision for Loss Product Expense Payables', 'Provision for Loss Product Expense Payables'), ('Hygiene and Sanitation Expenses Payables', 'Hygiene and Sanitation Expenses Payables'), ('Social Insurance Expense Payables', 'Social Insurance Expense Payables'), ('Rents Expense Payables', 'Rents Expense Payables'), ('Stationaries Payables', 'Stationaries Payables'), ('Direct Labour Expense Payables', 'Direct Labour Expense Payables'), ('InDirect Labour Expense Payables', 'InDirect Labour Expense Payables'), ('Fuel expense Payables', 'Fuel expense Payables'), ('Transportation Expense Payables', 'Transportation Expense Payables'), ('Gas Expense Payables', 'Gas Expense Payables'), ('Salary Expenses Payables', 'Salary Expenses Payables'), ('Allowance Expense Payables', 'Allowance Expense Payables'), ('Tax Expense Payables', 'Tax Expense Payables'), ('Depreciation Expense Payables', 'Depreciation Expense Payables')], default='', max_length=500, null=True, verbose_name='Account Credit')),
                ('due_date', models.DateField(blank=True, default='', null=True, verbose_name='Due Date')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('department', models.CharField(blank=True, choices=[('Bakery', 'Bakery'), ('Boulangerie', 'Boulangerie'), ('Supermarket', 'Supermarket'), ('Bar', 'Bar'), ('Snack', 'Snack'), ('Ice Cream', 'Ice Cream')], default='', max_length=500, null=True)),
                ('user_status', models.CharField(blank=True, choices=[('Employee', 'Employee'), ('Management', 'Management')], default='', max_length=500, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Invoice Id')),
                ('bank_reciept_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bank Reciept Id')),
                ('bank', models.CharField(default='', max_length=200, verbose_name='Bank Name')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.FloatField(default=0.0)),
                ('account_dr', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Bank', 'Bank')], default='', max_length=500, null=True, verbose_name='Account Debit')),
                ('account_cr', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Bank', 'Bank')], default='', max_length=500, null=True, verbose_name='Account Credit')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Bank',
            },
        ),
        migrations.CreateModel(
            name='AccountsRecievable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('department', models.CharField(blank=True, choices=[('Bakery', 'Bakery'), ('Boulangerie', 'Boulangerie'), ('Supermarket', 'Supermarket'), ('Bar', 'Bar'), ('Snack', 'Snack'), ('Ice Cream', 'Ice Cream'), ('WholeSale', 'WholeSale')], default='', max_length=500, null=True)),
                ('user_status', models.CharField(blank=True, choices=[('Employee', 'Employee'), ('Management', 'Management')], default='', max_length=500, null=True)),
                ('invoice_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Invoice Id')),
                ('sales_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Invoice Id')),
                ('customer', models.CharField(default='', max_length=200, verbose_name='Customer')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.FloatField(default=0.0)),
                ('account_dr', models.CharField(blank=True, choices=[('Accounts Recievable', 'AccountsRecievables'), ('Cash', 'Cash')], default='', max_length=500, null=True, verbose_name='Account Debit')),
                ('account_cr', models.CharField(blank=True, choices=[('Sales', 'Sales'), ('Accounts Recievable', 'AccountsRecievables')], default='', max_length=500, null=True, verbose_name='Account Credit')),
                ('due_date', models.DateField(blank=True, default='', null=True, verbose_name='Due Date')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AccountsRecievable',
                'verbose_name_plural': 'AccountsRecievables',
            },
        ),
        migrations.CreateModel(
            name='AccountsPayables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('department', models.CharField(blank=True, choices=[('Bakery', 'Bakery'), ('Boulangerie', 'Boulangerie'), ('Supermarket', 'Supermarket'), ('Bar', 'Bar'), ('Snack', 'Snack'), ('Ice Cream', 'Ice Cream'), ('WholeSale', 'WholeSale')], default='', max_length=500, null=True)),
                ('user_status', models.CharField(blank=True, choices=[('Employee', 'Employee'), ('Management', 'Management')], default='', max_length=500, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Invoice Id')),
                ('accnt_payables_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Stock Accnt Invoice Id')),
                ('supplier_institution', models.CharField(default='', max_length=200, verbose_name='Supplier/Institution')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.FloatField(default=0.0)),
                ('account_dr', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Airtime Expense Payables', 'Airtime Expense Payables'), ('Miscelleanous Expenses Payables', 'Miscelleanous Expenses Payables'), ('Tape expense Payables', 'Tape expense Payables'), ('Bike Maintanance Expense Payables', 'Bike Maintanance Expense Payables'), ('Bike Repairs Expense Payables', 'Bike Repairs Expense Payables'), ('Computer Repairs Expense Payables', 'Computer Repairs Expense Payables'), ('Cooler Maintainance expense Payables', 'Cooler Maintainance expense Payables'), ('Electrical repairs expense Payables', 'Electrical repairs expense Payables'), ('Fridge Repairs Expense Payables', 'Fridge Repairs Expense Payables'), ('Generator Maintainance Expense Payables', 'Generator Maintainance Expense Payables'), ('Internet Bill Expense Payables', 'Internet Bill Expense Payables'), ('Other Repairs Expense Payables', 'Other Repairs Expense Payables'), ('Oven Maintainance Expenses Payables', 'Oven Maintainance Expenses Payables'), ('Van Maintainance Expense Payables', 'Van Maintainance Expense Payables'), ('Van Repairs Expense Payables', 'Van Repairs Expense Payables'), ('Cable Expenses Payables', 'Cable Expenses Payables'), ('Electricity Bill Expense Payables', 'Electricity Bill Expense Payables'), ('Water Bill Expense Payables', 'Water Bill Expense Payables'), ('Charges expense Payables', 'Charges expense Payables'), ('Cleaning Expense Payables', 'Cleaning Expense Payables'), ('Commission Expense Payables', 'Commission Expense Payables'), ('Health Expense Payables', 'Health Expense Payables'), ('Insurance Expense Payables', 'Insurance Expense Payables'), ('Off Loading Expense Payables', 'Off Loading Expense Payables'), ('Provision for Loss Product Expense Payables', 'Provision for Loss Product Expense Payables'), ('Hygiene and Sanitation Expenses Payables', 'Hygiene and Sanitation Expenses Payables'), ('Social Insurance Expense Payables', 'Social Insurance Expense Payables'), ('Rents Expense Payables', 'Rents Expense Payables'), ('Stationaries Payables', 'Stationaries Payables'), ('Direct Labour Expense Payables', 'Direct Labour Expense Payables'), ('InDirect Labour Expense Payables', 'InDirect Labour Expense Payables'), ('Fuel expense Payables', 'Fuel expense Payables'), ('Transportation Expense Payables', 'Transportation Expense Payables'), ('Gas Expense Payables', 'Gas Expense Payables'), ('Salary Expenses Payables', 'Salary Expenses Payables'), ('Allowance Expense Payables', 'Allowance Expense Payables'), ('Tax Expense Payables', 'Tax Expense Payables'), ('Depreciation Expense Payables', 'Depreciation Expense Payables')], default='', max_length=500, null=True, verbose_name='Account Debit')),
                ('account_cr', models.CharField(blank=True, choices=[('Cash', 'Cash')], default='', max_length=500, null=True, verbose_name='Account Credit')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AccountsPayable',
                'verbose_name_plural': 'AccountsPayable',
            },
        ),
    ]
