# Generated by Django 4.0.3 on 2022-03-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_ledger', '0013_alter_purchases_options_expense_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditors',
            name='account_dr',
            field=models.CharField(blank=True, choices=[('Creditors', 'Creditors')], default='', max_length=500, null=True, verbose_name='Account Debit'),
        ),
    ]
