# Generated by Django 4.0.3 on 2022-03-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_ledger', '0015_alter_creditors_account_cr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='account_dr',
            field=models.CharField(blank=True, choices=[('Airtime Expense', 'Airtime Expense'), ('Miscelleanous Expenses', 'Miscelleanous Expenses'), ('Tape expense', 'Tape expense'), ('Bike Maintanance Expense', 'Bike Maintanance Expense'), ('Bike Repairs Expense', 'Bike Repairs Expense'), ('Computer Repairs Expense', 'Computer Repairs Expense'), ('Cooler Maintainance expense', 'Cooler Maintainance expense'), ('Electrical repairs expense', 'Electrical repairs expense'), ('Fridge Repairs Expense', 'Fridge Repairs Expense'), ('Generator Maintainance Expense', 'Generator Maintainance Expense'), ('Internet Bill Expense', 'Internet Bill Expense'), ('Other Repairs Expense', 'Other Repairs Expense'), ('Oven Maintainance expenses', 'Oven Maintainance expenses'), ('Van Maintainance expense', 'Van Maintainance expense'), ('Van Repairs Expense', 'Van Repairs Expense'), ('Cable Expenses', 'Cable Expenses'), ('Electricity Bill Expense', 'Electricity Bill Expense'), ('Water Bill Expense', 'Water Bill Expense'), ('Charges expense', 'Charges expense'), ('Cleaning Expense', 'Cleaning Expense'), ('Commission Expense', 'Commission Expense'), ('Health Expense', 'Health Expense'), ('Insurance Expense', 'Insurance Expense'), ('Off Loading Expense', 'Off Loading Expense'), ('Provision for Loss Product Expense', 'Provision for Loss Product Expense'), ('Hygiene and Sanitation Expenses', 'Hygiene and Sanitation Expenses'), ('Social Insurance Expense', 'Social Insurance Expense'), ('Rents Expense', 'Rents Expense'), ('Stationaries', 'Stationaries'), ('Direct Labour Expense', 'Direct Labour Expense'), ('InDirect Labour Expense', 'InDirect Labour Expense'), ('Fuel expense', 'Fuel expense'), ('Transportation Expense', 'Transportation Expense'), ('Gas Expense', 'Gas Expense'), ('Salary Expenses', 'Salary Expenses'), ('Allowance Expense', 'Allowance Expense'), ('Tax Expense', 'Tax Expense'), ('Depreciation Expense', 'Depreciation Expense'), ('Bank Charges Expense', 'Bank Charges Expense')], default='', max_length=500, null=True, verbose_name='Account Debit'),
        ),
    ]
