# Generated by Django 4.0.3 on 2022-03-06 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general_ledger', '0016_alter_expense_account_dr'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoansRecievable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('department', models.CharField(blank=True, choices=[('Bakery', 'Bakery'), ('Boulangerie', 'Boulangerie'), ('Supermarket', 'Supermarket'), ('Bar', 'Bar'), ('Snack', 'Snack'), ('Ice Cream', 'Ice Cream'), ('WholeSale', 'WholeSale')], default='', max_length=500, null=True)),
                ('user_status', models.CharField(blank=True, choices=[('Employee', 'Employee'), ('Management', 'Management')], default='', max_length=500, null=True)),
                ('loan_rec_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Loan Id')),
                ('beneficiary', models.CharField(default='', max_length=200, verbose_name='Beneficiary')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.FloatField(default=0.0)),
                ('account_dr', models.CharField(blank=True, choices=[('Loans Recievable', 'Loans Recievables'), ('Cash', 'Cash')], default='', max_length=500, null=True, verbose_name='Account Debit')),
                ('account_cr', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Loans Recievable', 'Loans Recievables')], default='', max_length=500, null=True, verbose_name='Account Credit')),
                ('due_date', models.DateField(blank=True, default='', null=True, verbose_name='Due Date')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LoansRecievable',
                'verbose_name_plural': 'LoansRecievables',
            },
        ),
        migrations.CreateModel(
            name='LoansPayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('department', models.CharField(blank=True, choices=[('Bakery', 'Bakery'), ('Boulangerie', 'Boulangerie'), ('Supermarket', 'Supermarket'), ('Bar', 'Bar'), ('Snack', 'Snack'), ('Ice Cream', 'Ice Cream'), ('WholeSale', 'WholeSale')], default='', max_length=500, null=True)),
                ('user_status', models.CharField(blank=True, choices=[('Employee', 'Employee'), ('Management', 'Management')], default='', max_length=500, null=True)),
                ('loan_rec_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Loan Id')),
                ('institution', models.CharField(default='', max_length=200, verbose_name='Institution')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.FloatField(default=0.0)),
                ('account_dr', models.CharField(blank=True, choices=[('Loans Recievable', 'Loans Recievables'), ('Cash', 'Cash')], default='', max_length=500, null=True, verbose_name='Account Debit')),
                ('account_cr', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Loans Recievable', 'Loans Recievables')], default='', max_length=500, null=True, verbose_name='Account Credit')),
                ('due_date', models.DateField(blank=True, default='', null=True, verbose_name='Due Date')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LoansPayable',
                'verbose_name_plural': 'LoansPayable',
            },
        ),
    ]
