# Generated by Django 4.0.3 on 2022-03-06 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BakerySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('order_no', models.IntegerField(max_length=200)),
                ('invoice_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Invoice Id')),
                ('supplier', models.CharField(blank=True, choices=[('Moses', 'Moses'), ('Glory', 'Glory'), ('Kesty', 'Kesty')], default='', max_length=500, null=True, verbose_name='Supplier')),
                ('customer', models.CharField(max_length=200, verbose_name='')),
                ('department', models.CharField(blank=True, choices=[('Bakery', 'Bakery')], default='Bakery', max_length=500, null=True, verbose_name='Department')),
                ('sub_department', models.CharField(blank=True, choices=[('Boulangerie', 'Boulangerie'), ('Patisserie', 'Patisserie')], default='Bakery', max_length=500, null=True, verbose_name='Sub Department')),
                ('category', models.CharField(blank=True, choices=[('Bread', 'Bread'), ('Confectionary', 'Confectionary'), ('Hamburger', 'Hamburger'), ('Sandwich', 'Sandwich'), ('Cake', 'Cake'), ('Milk Bread', 'Milk Bread'), ('Biscuit', 'Biscuit'), ('Croissant', 'Croissant'), ('Fruitage', 'Fruitage')], default='', max_length=500, null=True)),
                ('session', models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Evening', 'Evening')], default='', max_length=500, null=True, verbose_name='Session')),
                ('product', models.CharField(max_length=200, verbose_name='Product Name')),
                ('qty', models.IntegerField(verbose_name='Quantity')),
                ('total_amount', models.FloatField(default=0.0)),
                ('discount', models.FloatField(default=0.0, verbose_name='Discount')),
                ('discount_value', models.FloatField(default=0.0, verbose_name='Discount Value')),
                ('net_amount', models.FloatField(default=0.0, verbose_name='Net Amount')),
                ('commission', models.FloatField(default=0.0, verbose_name='Commission')),
                ('due_date', models.DateField(blank=True, default='', null=True, verbose_name='Due Date')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BakerySales',
                'verbose_name_plural': 'BakerySales',
            },
        ),
    ]
