# Generated by Django 4.0.3 on 2022-03-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakerysales',
            name='order_no',
            field=models.IntegerField(),
        ),
    ]
