# Generated by Django 4.0.3 on 2022-03-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0003_alter_bakerysales_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakerysales',
            name='cost_price',
            field=models.FloatField(default=0.0, verbose_name='Cost Price'),
        ),
    ]
