# Generated by Django 4.0.3 on 2022-03-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0004_bakerysales_cost_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakerysales',
            name='due_date',
        ),
    ]
