# Generated by Django 4.0.3 on 2022-03-07 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bakery', '0005_remove_bakerysales_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BakeryCollector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('collector', models.CharField(max_length=200, verbose_name='Collector')),
            ],
            options={
                'verbose_name': 'BakeryCollector',
                'verbose_name_plural': 'BakeryCollectors',
            },
        ),
        migrations.CreateModel(
            name='BakeryReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('order_no', models.IntegerField()),
                ('return_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Return Invoice Id')),
                ('invoice_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Invoice Id')),
                ('customer_from', models.CharField(max_length=200, verbose_name='Customer')),
                ('customer_to', models.CharField(max_length=200, verbose_name='Customer')),
                ('department', models.CharField(blank=True, choices=[('Bakery', 'Bakery')], default='Bakery', max_length=500, null=True, verbose_name='Department')),
                ('sub_department', models.CharField(blank=True, choices=[('Boulangerie', 'Boulangerie'), ('Patisserie', 'Patisserie')], default='Bakery', max_length=500, null=True, verbose_name='Sub Department')),
                ('category', models.CharField(blank=True, choices=[('Bread', 'Bread'), ('Confectionary', 'Confectionary'), ('Hamburger', 'Hamburger'), ('Sandwich', 'Sandwich'), ('Cake', 'Cake'), ('Milk Bread', 'Milk Bread'), ('Biscuit', 'Biscuit'), ('Croissant', 'Croissant'), ('Fruitage', 'Fruitage')], default='', max_length=500, null=True)),
                ('product', models.CharField(max_length=200, verbose_name='Product Name')),
                ('qty', models.IntegerField(verbose_name='Quantity')),
                ('cost_price', models.FloatField(default=0.0, verbose_name='Cost Price')),
                ('total_amount', models.FloatField(default=0.0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BakeryReturns',
                'verbose_name_plural': 'BakeryReturns',
            },
        ),
        migrations.CreateModel(
            name='BakeryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('payment_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Payment Invoice Id')),
                ('customer', models.CharField(max_length=200, verbose_name='Customer')),
                ('department', models.CharField(blank=True, choices=[('Bakery', 'Bakery')], default='Bakery', max_length=500, null=True, verbose_name='Department')),
                ('amount', models.FloatField(default=0.0, verbose_name='Amount')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery.bakerycollector')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BakeryPayment',
                'verbose_name_plural': 'BakeryPayments',
            },
        ),
        migrations.CreateModel(
            name='BakeryOpeningBalances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('openingbalance_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Opening Balance Id')),
                ('customer', models.CharField(max_length=200, verbose_name='Customer')),
                ('department', models.CharField(blank=True, choices=[('Bakery', 'Bakery')], default='Bakery', max_length=500, null=True, verbose_name='Department')),
                ('amount', models.FloatField(default=0.0, verbose_name='Amount')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BakeryCollector',
                'verbose_name_plural': 'BakeryCollectors',
            },
        ),
    ]
