# Generated by Django 4.0.3 on 2022-03-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0006_bakerycollector_bakeryreturn_bakerypayment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bakeryopeningbalances',
            options={'verbose_name': 'BakeryOpeningBalance', 'verbose_name_plural': 'BakeryOpeningBalances'},
        ),
        migrations.AddField(
            model_name='bakeryopeningbalances',
            name='ob_no',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='OB No'),
        ),
    ]
