# Generated by Django 4.0.3 on 2022-03-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0009_alter_bakerypayment_collector'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakerypayment',
            name='session',
            field=models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Evening', 'Evening')], default='', max_length=500, null=True, verbose_name='Session'),
        ),
    ]
