# Generated by Django 4.0.3 on 2022-03-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0010_bakerypayment_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakerypayment',
            name='collector',
            field=models.CharField(blank=True, choices=[('Moses', 'Moses'), ('Glory', 'Glory'), ('Kesty', 'Kesty'), ('Charles', 'Charles'), ('Cyril', 'Cyril'), ('Aly', 'Aly'), ('Joan', 'Joan'), ('Micheal', 'Micheal'), ('Esther', 'Esther'), ('Violet', 'Violet'), ('Kaba', 'Kaba')], max_length=500, null=True, verbose_name='Collector'),
        ),
    ]
