# Generated by Django 4.0.3 on 2022-03-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0011_alter_bakerypayment_collector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakeryreturn',
            name='customer_from',
            field=models.CharField(max_length=200, verbose_name='Customer_from'),
        ),
        migrations.AlterField(
            model_name='bakeryreturn',
            name='customer_to',
            field=models.CharField(max_length=200, verbose_name='Customer_to'),
        ),
    ]
