# Generated by Django 4.0.3 on 2022-03-10 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bakery', '0012_alter_bakeryreturn_customer_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakerysales',
            name='supplier',
            field=models.CharField(blank=True, choices=[('Moses', 'Moses'), ('Glory', 'Glory'), ('KESTY', 'KESTY')], default='', max_length=500, null=True, verbose_name='Supplier'),
        ),
        migrations.CreateModel(
            name='BakeryRmReturns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('department', models.CharField(blank=True, choices=[('Bakery', 'Bakery')], default='Bakery', max_length=500, null=True, verbose_name='Department')),
                ('procuement_manager', models.CharField(max_length=200, verbose_name='Procuement Manager')),
                ('purchase_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Purchase Invoice Id')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('supplier', models.CharField(max_length=200, verbose_name='Supplier')),
                ('category', models.CharField(blank=True, choices=[('Direct', 'Direct'), ('Indirect', 'Indirect')], default='Direct', max_length=500, null=True, verbose_name='Category')),
                ('entry_measure', models.CharField(max_length=200, verbose_name='Entry Measure')),
                ('weight_pack', models.CharField(max_length=200, verbose_name='Weight/Pack')),
                ('product', models.CharField(max_length=200, verbose_name='Product')),
                ('qty', models.FloatField(default=0.0, verbose_name='Quantity')),
                ('unit_cost_price', models.FloatField(default=0.0, verbose_name='Unit Cost Price')),
                ('total_cost_price', models.FloatField(default=0.0, verbose_name='Total Cost Price')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BakeryRmReturn',
                'verbose_name_plural': 'BakeryPRmReturns',
            },
        ),
        migrations.CreateModel(
            name='BakeryRmDamages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('department', models.CharField(blank=True, choices=[('Bakery', 'Bakery')], default='Bakery', max_length=500, null=True, verbose_name='Department')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('damage_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Purchase Invoice Id')),
                ('category', models.CharField(blank=True, choices=[('Direct', 'Direct'), ('Indirect', 'Indirect')], default='Direct', max_length=500, null=True, verbose_name='Category')),
                ('entry_measure', models.CharField(max_length=200, verbose_name='Entry Measure')),
                ('weight_pack', models.CharField(max_length=200, verbose_name='Weight/Pack')),
                ('product', models.CharField(max_length=200, verbose_name='Product')),
                ('qty', models.FloatField(default=0.0, verbose_name='Quantity')),
                ('unit_cost_price', models.FloatField(default=0.0, verbose_name='Unit Cost Price')),
                ('total_cost_price', models.FloatField(default=0.0, verbose_name='Total Cost Price')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BakeryRmDamage',
                'verbose_name_plural': 'BakeryRmDamages',
            },
        ),
        migrations.CreateModel(
            name='BakeryPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('department', models.CharField(blank=True, choices=[('Bakery', 'Bakery')], default='Bakery', max_length=500, null=True, verbose_name='Department')),
                ('procuement_manager', models.CharField(max_length=200, verbose_name='Procuement Manager')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('purchase_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Purchase Invoice Id')),
                ('supplier', models.CharField(max_length=200, verbose_name='Supplier')),
                ('category', models.CharField(blank=True, choices=[('Direct', 'Direct'), ('Indirect', 'Indirect')], default='Direct', max_length=500, null=True, verbose_name='Category')),
                ('entry_measure', models.CharField(max_length=200, verbose_name='Entry Measure')),
                ('weight_pack', models.CharField(max_length=200, verbose_name='Weight/Pack')),
                ('product', models.CharField(max_length=200, verbose_name='Product')),
                ('qty', models.FloatField(default=0.0, verbose_name='Quantity')),
                ('unit_cost_price', models.FloatField(default=0.0, verbose_name='Unit Cost Price')),
                ('total_cost_price', models.FloatField(default=0.0, verbose_name='Total Cost Price')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BakeryPurchase',
                'verbose_name_plural': 'BakeryPurchases',
            },
        ),
        migrations.CreateModel(
            name='BakeryInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('department', models.CharField(blank=True, choices=[('Bakery', 'Bakery')], default='Bakery', max_length=500, null=True, verbose_name='Department')),
                ('sub_department', models.CharField(blank=True, choices=[('Boulangerie Morning', 'Boulangerie Morning'), ('Boulangerie Evening', 'Boulangerie Evening'), ('Patisserie', 'Patisserie')], default='', max_length=500, null=True, verbose_name='Sub Department')),
                ('stock_status', models.CharField(blank=True, choices=[('Boulangerie Morning', 'Boulangerie Morning'), ('Boulangerie Evening', 'Boulangerie Evening'), ('Patisserie', 'Patisserie')], default='', max_length=500, null=True, verbose_name='Stock Status')),
                ('entry_measure', models.FloatField(default=0.0, verbose_name='Entry Measure')),
                ('product', models.CharField(max_length=200, verbose_name='Product')),
                ('qty', models.FloatField(default=0.0, verbose_name='Quantity')),
                ('unit_cost_price', models.FloatField(default=0.0, verbose_name='Unit Cost Price')),
                ('total_cost_price', models.FloatField(default=0.0, verbose_name='Total Cost Price')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BakeryInventory',
                'verbose_name_plural': 'BakeryInventory',
            },
        ),
    ]
