# Generated by Django 4.0.3 on 2022-03-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0013_alter_bakerysales_supplier_bakeryrmreturns_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakeryinventory',
            name='stock_status',
            field=models.CharField(blank=True, choices=[('Opening Stock', 'Opening Stock'), ('Closing Stock', 'Closing Stock')], default='', max_length=500, null=True, verbose_name='Stock Status'),
        ),
    ]
